plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  instance-state-name: running

hostnames:
  - tag:Name   # ✅ use NAME tag as hostname

compose:
  ansible_user: >
    {{
      'ubuntu' if (platform_details | lower is search('ubuntu'))
      else 'ec2-user'
    }}
